# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.101.1"

default_platform :ios

platform :ios do

  desc "This lane will run before execution of other lane."
  before_all do
    xcode_location = ENV['XCODE_LOCATION']
    xcode_select(xcode_location)
  end

  desc "This lane will ensure that current Xcode version is selected for BreatheMapper project."
  lane :ensure_xcode_version_for_release do
    ensure_xcode_version(
      version: ENV['XCODE_VERSION']
    )
  end

  desc "This lane will ensure that current Git branch BreatheMapper project is develop."
  lane :ensure_git_branch_for_alpha_release do
    ensure_git_branch(
      branch: ENV['GIT_BRANCH_FOR_ALPHA_RELEASE']
    )
  end

  desc "This lane will ensure that there is no local changes in BreatheMapper project Git Repo."
  lane :ensure_clean_git_status do
    ensure_git_status_clean(
      show_uncommitted_changes: true
    )
  end

  desc "This lane will run unit test-cases of BreatheMapper project."
  lane :run_unit_test_cases do
    run_tests(
      scheme: ENV['APP_TARGET'],
      configuration: ENV['DEFAULT_CONFIGURATION'],
      only_testing: ENV['APP_UNIT_TESTCASES_TARGET']
    )
  end

  desc "This lane will run UI test-cases of BreatheMapper project."
  lane :run_ui_test_cases do
    run_tests(
      scheme: ENV['APP_TARGET'],
      configuration: ENV['DEFAULT_CONFIGURATION'],
      only_testing: ENV['APP_UI_TESTCASES_TARGET']
    )
  end

  desc "This lane will run Unit and UI both type test-cases of BreatheMapper project in iOS10 simulator."
  lane :run_all_test_cases_ios10 do |options|
    simulator_info = options[:simulator_info]
    name = (simulator_info.split('|'))[0]
    os = (simulator_info.split('|'))[1]
    run_tests(
      scheme: ENV['APP_TARGET'],
      configuration: ENV['DEFAULT_CONFIGURATION'],
      destination: ENV['SIMULATOR_iOS'] % {:name => name, :os => os}
    )
  end

  desc "This lane will run Unit and UI both type test-cases of BreatheMapper project in iOS11 simulator."
  lane :run_all_test_cases_ios11 do |options|
    simulator_info = options[:simulator_info]
    name = (simulator_info.split('|'))[0]
    os = (simulator_info.split('|'))[1]
    run_tests(
      scheme: ENV['APP_TARGET'],
      configuration: ENV['DEFAULT_CONFIGURATION'],
      destination: ENV['SIMULATOR_iOS'] % {:name => name, :os => os}
    )
  end

  desc "This lane will generate code-coverage report of BreatheMapper project."
  lane :generate_code_coverage_report do
    slather(
      scheme: ENV['APP_TARGET'],
      configuration: ENV['DEFAULT_CONFIGURATION'],
      proj: ENV['PROJ'],
      workspace: ENV['WORKSPACE'],
      output_directory: ENV['CODE_COVERAGE_DIR'],
      html: true
    )
  end

end