# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MySpeaker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Branch'

  # Pods for MySpeaker

  target 'MySpeakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MySpeakerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
